# Generated by Django 4.1 on 2022-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
