# Generated by Django 4.1 on 2022-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('matriz_curricular', models.CharField(max_length=9)),
                ('data_vigor', models.DateField()),
            ],
        ),
    ]
