# Generated by Django 4.1 on 2022-09-13 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=100)),
                ('grau', models.CharField(choices=[('B', 'Bacharelado'), ('L', 'Licenciatura'), ('T', 'Tecnólogo')], max_length=15)),
                ('instituicao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('CPF', models.IntegerField(unique=True)),
                ('BORN', models.DateField()),
                ('ENDERECO', models.CharField(max_length=50)),
                ('SALARIO', models.FloatField()),
                ('TITULO', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='professor.titulo')),
            ],
        ),
    ]
