# Generated by Django 4.1 on 2022-09-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma_semestre',
            name='cadeiras',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='disciplina.disciplina'),
        ),
        migrations.DeleteModel(
            name='disciplina',
        ),
    ]
